### ISSUE TITLE
New User Sign Up

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-dashboard#1103] opened 2016-04-11 08:16 UTC
On new user sign up. Upon wrong data entries, notifications are not as good as they should be.

Please get the reference from [New User creation](https://github.com/evercam/evercam-api/issues/610)

<img width="641" alt="44507778-f1bb-11e5-9786-94f9844d2b7d" src="https://cloud.githubusercontent.com/assets/13561999/14420820/7c156440-ffe7-11e5-877c-0f7681d3f3ad.png">

**Comment by muneeb2542** [comment] 2016-04-14 09:16
@liutingdu can you tell me a bit about how you got this message because right now I'm getting this message on sign up.

![screenshot from 2016-04-14 14-13-14](https://cloud.githubusercontent.com/assets/6482077/14523071/21fcfe94-024b-11e6-8361-35b14fadd3bc.png)

**Comment by liutingdu** [comment] 2016-04-14 09:32
@muneeb2542 I am not able to reproduce it now, Possible has been fixed by others?

**Comment by liutingdu** [comment] 2016-04-14 09:34
@muneeb2542 Oh sorry, just tried it again, I am still able to reproduce it by clicking button 'Create New Account'

**Comment by muneeb2542** [comment] 2016-04-18 06:09
This bug was fixed in #1117 

Closing this.

**Closed by muneeb2542** 2016-04-18 06:09 UTC
