### ISSUE TITLE
Looks like intercom isn't working properly.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#812] opened 2015-11-30 12:08 UTC
![screenshot-app intercom io 2015-11-30 12-05-40](https://cloud.githubusercontent.com/assets/5648894/11471120/df95765e-975a-11e5-968e-666bf137ff90.png)

We're recording new users & sessions, but not getting the full picture. 

Perhaps we've enabled it on API, but incompletely?
Perhaps it also needs enabling on Dash ?
PS. @liutingdu  is also enabling this on Android, sometime this week.

**Comment by marcoherbst** [comment] 2015-12-03 10:07
@liutingdu , can I ask you please to close this task when you think it's done.

**Comment by liutingdu** [comment] 2015-12-03 12:08
Seems this issue is about "Why this user has two web sessions but missing related info like USER ID, BROWSER, OS.."

@azharmalik3  has added USER ID for all users by running a Rake task. He also added code to update web related info every time when user signed in. 

@marcoherbst Since you didn't say which user it is and also didn't provide steps to reproduce it, I am not seeing this happen any more, I think the task is done.

I've noticed there are many other Intercom related issues, I'll close this one and create new issues for them.

**Comment by liutingdu** [comment] 2015-12-03 12:30
Reopen this because I am able to reproduce it now. 

@azharmalik3 It's happening if a user creates an account from the dashboard, all info related to that user is empty if they don't sign in again. Could you fix this ?

**Comment by liutingdu** [comment] 2015-12-07 10:58
Thanks @azharmalik3 , It's working now :+1:  I'll close this.

**Closed by liutingdu** 2015-12-07 10:58 UTC
